version: 2
jobs:
  build:
    environment:
      CC_TEST_REPORTER_ID: e4fdf9e3c5e133ef6be74f05ac49fdd0bd604369fffae4fdea3950ea23d33bd6
    docker:
      - image: circleci/php:7.4.0-apache
        environment:
      - image: circleci/postgres:12.1-postgis-ram
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: altitude-api-test
          POSTGRES_PASSWORD: password
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install System Packages
          command: sudo apt update & sudo apt install -y git unzip zlib1g-dev
      - run:
          name: Install PostgreSQL client tools
          command: |
            sudo apt update && sudo apt install postgresql-client
      - run:
          name: Install PHP Extensions
          command: |
            sudo apt update && sudo apt install libpq-dev
            sudo docker-php-ext-install zip pdo_pgsql && sudo docker-php-ext-enable pdo_pgsql
      - run:
          name: Install Composer
          command: |
            php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
            php -r "copy('https://composer.github.io/installer.sig', 'composer-setup.sig');"
            php -r "if (hash_file('SHA384', 'composer-setup.php') === trim(file_get_contents('composer-setup.sig'))) { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
            php composer-setup.php
            php -r "unlink('composer-setup.php');"
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}
            - v1-dependencies-
      - run:
          name: Install Project Dependencies
          command: composer install -n --prefer-dist
      - run:
          name: Setup Code Climate test-reporter
          command: |
            sudo pecl channel-update pecl.php.net
            sudo pecl install xdebug && sudo docker-php-ext-enable xdebug
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
            sudo mkdir -p $CIRCLE_TEST_REPORTS/phpunit
      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor
      - run:
          name: Initialise Database
          command: |
            php artisan migrate:refresh --env=testing --force
            php artisan db:seed
      - run:
          name: Run Tests
          command: |
            ./cc-test-reporter before-build
            sudo ./vendor/bin/phpunit --coverage-clover clover.xml
            ./cc-test-reporter after-build --coverage-input-type clover --exit-code $?
